// <auto-generated />
namespace Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v23));
        
        string IMigrationMetadata.Id
        {
            get { return "201902020549563_v23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
