// <auto-generated />
namespace Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V78 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V78));
        
        string IMigrationMetadata.Id
        {
            get { return "202007290815125_V78"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
