//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TourHotelsPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TourHotelsPackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Models.TourHotelsPackage", typeof(TourHotelsPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کودک با تخت.
        /// </summary>
        public static string ChildWithBedPrice {
            get {
                return ResourceManager.GetString("ChildWithBedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر شب اضافه کودک با تخت.
        /// </summary>
        public static string ChildWithBedPrice_ExtraNight {
            get {
                return ResourceManager.GetString("ChildWithBedPrice_ExtraNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کودک بدون تخت.
        /// </summary>
        public static string ChildWithoutBedPrice {
            get {
                return ResourceManager.GetString("ChildWithoutBedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر شب اضافه کودک بدون تخت.
        /// </summary>
        public static string ChildWithoutBedPrice_ExtraNight {
            get {
                return ResourceManager.GetString("ChildWithoutBedPrice_ExtraNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت اتاق یک تخته.
        /// </summary>
        public static string OneBedRoomPrice {
            get {
                return ResourceManager.GetString("OneBedRoomPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر شب اضافه اتاق یک تخته.
        /// </summary>
        public static string OneBedRoomPrice_ExtraNight {
            get {
                return ResourceManager.GetString("OneBedRoomPrice_ExtraNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت اتاق دو تخته.
        /// </summary>
        public static string TwoBedRoomPrice {
            get {
                return ResourceManager.GetString("TwoBedRoomPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر شب اضافه اتاق دو تخته.
        /// </summary>
        public static string TwoBedRoomPrice_ExtraNight {
            get {
                return ResourceManager.GetString("TwoBedRoomPrice_ExtraNight", resourceCulture);
            }
        }
    }
}
